const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let currentUser=JSON.parse(localStorage.getItem('orivox_user')||'null');
let currentConversation=null,mediaRecorder=null,mediaStream=null,audioChunks=[],audioCtx=null,analyser=null,animId=null,currentAudio=null,settings={};
const state={history:[],status:null};

function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),3200)}
async function api(url,opts={}){const headers={...(opts.headers||{})};if(opts.body&&!(opts.body instanceof FormData)&&!headers['Content-Type'])headers['Content-Type']='application/json';let r;try{r=await fetch(url,{...opts,headers})}catch{throw new Error('ORIVOX local service is unavailable. Restart ORIVOX and try again.')}if(!r.ok){let m=`Request failed (${r.status})`;try{const j=await r.json();m=j.detail||j.message||m}catch{}throw new Error(m)}const ct=r.headers.get('content-type')||'';return ct.includes('application/json')?r.json():r.blob()}
function applyTheme(mode){const dark=mode==='dark'||(mode==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.body.classList.toggle('dark',dark);localStorage.setItem('orivox_theme',mode);const toggle=$('#themeToggle');if(toggle)toggle.textContent=dark?'☾':'☼'}
function initials(name='ORIVOX'){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'O'}
function syncUserUI(){if(!currentUser)return;const label=currentUser.email||currentUser.name||'Local account';$('#sidebarUser').textContent=label;const mark=initials(currentUser.name);['#sidebarAvatar','#topAvatar','#profileAvatar'].forEach(id=>{const el=$(id);if(el)el.textContent=mark});$('#welcome').innerHTML=`Welcome back, ${escapeHtml(currentUser.name)}.<br><em>ORIVOX is ready.</em>`}
function showAuth(){ $('#auth').classList.remove('hidden');$('#app').classList.add('hidden') }
function showApp(){ $('#auth').classList.add('hidden');$('#app').classList.remove('hidden');syncUserUI();switchView('dashboard');loadAll() }
const viewMeta={dashboard:['Overview','LOCAL AI WORKSPACE'],voice:['Voice Assistant','VOICE WORKSPACE'],history:['Conversations','YOUR LOCAL MEMORY'],profile:['Profile','LOCAL ACCOUNT'],settings:['Settings','MAKE ORIVOX YOURS'],about:['Help & About','HR-PRESENTS ORIVOX']};
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===name));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===name));const meta=viewMeta[name]||[name,'ORIVOX'];$('#pageTitle').textContent=meta[0];const eyebrow=$('#pageEyebrow');if(eyebrow)eyebrow.textContent=meta[1];window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$$('[data-auth]').forEach(b=>b.addEventListener('click',()=>{const login=b.dataset.auth==='login';$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$('#loginForm').classList.toggle('hidden',!login);$('#registerForm').classList.toggle('hidden',login);$('#authHeading').textContent=login?'Sign in to your workspace':'Create your local workspace'}));
$$('[data-toggle-password]').forEach(b=>b.onclick=()=>{const i=document.getElementById(b.dataset.togglePassword);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Show':'Hide'});
function setFormBusy(form,busy,label){const btn=form.querySelector('button[type="submit"]');if(!btn)return;if(!btn.dataset.original)btn.dataset.original=btn.innerHTML;btn.disabled=busy;btn.innerHTML=busy?label:btn.dataset.original}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;setFormBusy(form,true,'Signing in…');try{const u=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value})});currentUser=u;localStorage.setItem('orivox_user',JSON.stringify(u));toast(`Welcome back, ${u.name}`);showApp()}catch(err){toast(err.message)}finally{setFormBusy(form,false,'')}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;if($('#registerPassword').value!==$('#registerConfirm').value)return toast('Passwords do not match');setFormBusy(form,true,'Creating local account…');try{const u=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:$('#registerName').value.trim(),email:$('#registerEmail').value.trim(),password:$('#registerPassword').value})});currentUser=u;localStorage.setItem('orivox_user',JSON.stringify(u));toast('Your local ORIVOX account is ready');showApp()}catch(err){toast(err.message)}finally{setFormBusy(form,false,'')}};
$('#logoutBtn').onclick=()=>{stopEverything();currentUser=null;currentConversation=null;state.history=[];localStorage.removeItem('orivox_user');showAuth();toast('Signed out of this local workspace')};

function statusLabel(value){return String(value||'unknown').replace(/_/g,' ')}
async function loadStatus(){try{state.status=await api('/api/status');const model=state.status.llm||'Local model';$('#statModel').textContent=model;$('#settingsModel').textContent=model;$('#aboutVersion').textContent=state.status.version||'—';const entries=Object.entries(state.status.models||{});$('#modelStatus').innerHTML=entries.length?entries.map(([k,v])=>`<div class="model-line"><span>${escapeHtml(k.toUpperCase())}</span><strong class="${escapeHtml(v)}">${escapeHtml(statusLabel(v))}</strong></div>`).join(''):'<div class="list-row"><strong>Runtime</strong><div class="muted">Model status appears after first use</div></div>';const ok=entries.length===0||entries.every(([,v])=>['ready','idle'].includes(v));$('#statusBadge').innerHTML=`<span class="live-dot"></span>${ok?'Local systems ready':'Check local models'}`;const sm=$('#sidebarModel');if(sm)sm.textContent=`${model} • ${ok?'ready':'attention needed'}`}catch(e){$('#statusBadge').textContent='Status unavailable';const sm=$('#sidebarModel');if(sm)sm.textContent='Local status unavailable'}}
async function loadHistory(){if(!currentUser)return;try{state.history=await api(`/api/conversations/${currentUser.id}`);renderHistory();$('#statConversations').textContent=state.history.length;$('#statMessages').textContent=state.history.reduce((a,c)=>a+Number(c.message_count||0),0);$('#recentList').innerHTML=state.history.slice(0,5).map(c=>`<button class="list-row recent-button" onclick="openConversation(${c.id})"><strong>${escapeHtml(c.title)}</strong><div class="muted">${Number(c.message_count||0)} messages →</div></button>`).join('')||'<div class="empty-inline"><strong>No conversations yet</strong><span>Start your first voice conversation.</span></div>'}catch(e){if(e.message.toLowerCase().includes('session'))return forceSignOut(e.message);toast(e.message)}}
function renderHistory(){const q=($('#historySearch').value||'').toLowerCase();const rows=state.history.filter(c=>(c.title||'').toLowerCase().includes(q));$('#historyList').innerHTML=rows.map(c=>`<article class="card history-item"><div><span class="kicker">LOCAL CONVERSATION</span><h3>${escapeHtml(c.title)}</h3><div class="muted">${Number(c.message_count||0)} messages${c.updated_at?` • ${formatDate(c.updated_at)}`:''}</div></div><div class="history-actions"><button class="ghost" onclick="openConversation(${c.id})">Open</button><button class="ghost danger" onclick="deleteConversation(${c.id})">Delete</button></div></article>`).join('')||'<div class="panel empty-inline"><strong>No conversations found</strong><span>Your real ORIVOX history will appear here.</span></div>'}
function formatDate(value){try{return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value))}catch{return''}}
window.openConversation=async id=>{try{const c=await api(`/api/conversations/${currentUser.id}/${id}`);currentConversation=c.id;renderMessages(c.messages||[]);switchView('voice');setVoiceState('Ready','Continue this conversation by speaking or typing.')}catch(e){toast(e.message)}};
window.deleteConversation=async id=>{if(!confirm('Delete this local conversation permanently?'))return;try{await api(`/api/conversations/${currentUser.id}/${id}`,{method:'DELETE'});if(currentConversation===id){currentConversation=null;renderMessages([])}toast('Conversation deleted');await loadHistory()}catch(e){toast(e.message)}};
$('#historySearch').oninput=renderHistory;$('#refreshHistory').onclick=loadHistory;

async function loadProfile(){try{const p=await api(`/api/profile/${currentUser.id}`);currentUser=p;localStorage.setItem('orivox_user',JSON.stringify(p));$('#profileName').value=p.name;$('#profileEmail').value=p.email;syncUserUI()}catch(e){if(e.message.toLowerCase().includes('session'))return forceSignOut(e.message);toast(e.message)}}
$('#profileForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;setFormBusy(form,true,'Saving…');try{const p=await api(`/api/profile/${currentUser.id}`,{method:'PUT',body:JSON.stringify({name:$('#profileName').value.trim(),email:$('#profileEmail').value.trim(),current_password:$('#profileCurrentPassword').value||null,new_password:$('#profileNewPassword').value||null})});currentUser=p;localStorage.setItem('orivox_user',JSON.stringify(p));syncUserUI();$('#profileCurrentPassword').value='';$('#profileNewPassword').value='';toast('Profile changes saved locally')}catch(e){toast(e.message)}finally{setFormBusy(form,false,'')}};
async function loadSettings(){try{settings=await api(`/api/settings/${currentUser.id}`);$('#settingTheme').value=settings.theme||'system';$('#settingVoice').value=settings.voice||'af_heart';$('#settingSpeed').value=settings.speed||'1.0';$('#settingVolume').value=settings.volume||'1.0';$('#settingAutoSpeak').checked=settings.auto_speak!=='false';$('#settingSaveAudio').checked=settings.save_audio==='true';applyTheme(settings.theme||'system')}catch(e){toast(e.message)}}
$('#saveSettings').onclick=async()=>{const btn=$('#saveSettings');const original=btn.textContent;btn.disabled=true;btn.textContent='Saving…';const values={theme:$('#settingTheme').value,voice:$('#settingVoice').value,speed:$('#settingSpeed').value,volume:$('#settingVolume').value,auto_speak:$('#settingAutoSpeak').checked,save_audio:$('#settingSaveAudio').checked};try{settings=await api(`/api/settings/${currentUser.id}`,{method:'PUT',body:JSON.stringify({values})});applyTheme(settings.theme||values.theme);toast('Settings saved on this device')}catch(e){toast(e.message)}finally{btn.disabled=false;btn.textContent=original}};
$('#themeToggle').onclick=()=>{const next=document.body.classList.contains('dark')?'light':'dark';applyTheme(next);$('#settingTheme').value=next};

function emptyConversation(){return '<div class="empty-state"><span>✦</span><strong>Your conversation starts here</strong><p>Speak or type a message. Real messages will appear here and be saved to local history.</p></div>'}
function renderMessages(msgs){const box=$('#messages');if(!msgs.length){box.innerHTML=emptyConversation();return}box.innerHTML=msgs.map(m=>`<div class="message ${escapeHtml(m.role)}"><span>${m.role==='user'?'You':'ORIVOX'}</span>${escapeHtml(m.content)}</div>`).join('');box.scrollTop=box.scrollHeight}
function appendMessage(role,text){const box=$('#messages');const empty=box.querySelector('.empty-state');if(empty)box.innerHTML='';const d=document.createElement('div');d.className=`message ${role}`;const who=document.createElement('span');who.textContent=role==='user'?'You':'ORIVOX';d.appendChild(who);d.appendChild(document.createTextNode(text));box.appendChild(d);box.scrollTop=box.scrollHeight}
function setVoiceState(s,hint=''){ $('#voiceState').textContent=s;if(hint)$('#voiceHint').textContent=hint;const prompt=$('#voicePrompt');if(prompt){const map={Listening:'I’m listening…',Transcribing:'Turning your voice into text…',Thinking:'Thinking locally…',Speaking:'ORIVOX is speaking…',Error:'Something needs attention',Ready:'What would you like to talk about?'};prompt.textContent=map[s]||s}}
async function sendText(text){text=(text||'').trim();if(!text||!currentUser)return;appendMessage('user',text);setVoiceState('Thinking','Your configured local AI model is generating a response.');$('#sendBtn').disabled=true;try{const r=await api('/api/chat',{method:'POST',body:JSON.stringify({user_id:currentUser.id,conversation_id:currentConversation,text})});currentConversation=r.conversation_id;const reply=r.text||r.response||'';appendMessage('assistant',reply);setVoiceState('Ready','Response complete. Continue speaking whenever you’re ready.');await loadHistory();if(settings.auto_speak!=='false'&&reply)await speak(reply)}catch(e){setVoiceState('Error',e.message);toast(e.message)}finally{$('#sendBtn').disabled=false}}
$('#sendBtn').onclick=()=>{const t=$('#textInput').value;$('#textInput').value='';sendText(t)};$('#textInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#sendBtn').click()}});
async function speak(text){stopAudio();setVoiceState('Speaking','Kokoro is generating speech locally.');try{const blob=await api('/api/speech',{method:'POST',body:JSON.stringify({text,voice:settings.voice||'af_heart',speed:Number(settings.speed||1)})});const url=URL.createObjectURL(blob);currentAudio=new Audio(url);currentAudio.volume=Number(settings.volume||1);currentAudio.onended=()=>{URL.revokeObjectURL(url);currentAudio=null;setVoiceState('Ready','Press the microphone and speak naturally.')};await currentAudio.play()}catch(e){setVoiceState('Error',e.message);toast(e.message)}}
function stopAudio(){if(currentAudio){currentAudio.pause();currentAudio.currentTime=0;currentAudio=null}}
function stopVisualizer(){if(animId)cancelAnimationFrame(animId);animId=null;const v=$('#visualizer');if(v)v.innerHTML='';if(audioCtx){audioCtx.close();audioCtx=null}}
function startVisualizer(stream){stopVisualizer();audioCtx=new (window.AudioContext||window.webkitAudioContext)();const src=audioCtx.createMediaStreamSource(stream);analyser=audioCtx.createAnalyser();analyser.fftSize=128;src.connect(analyser);const bars=Array.from({length:34},()=>{const b=document.createElement('div');b.className='bar';$('#visualizer').appendChild(b);return b});const data=new Uint8Array(analyser.frequencyBinCount);const draw=()=>{analyser.getByteFrequencyData(data);bars.forEach((b,i)=>b.style.height=`${Math.max(5,(data[(i*2)%data.length]||0)/2.25)}px`);animId=requestAnimationFrame(draw)};draw()}
async function startRecording(){stopAudio();if(!navigator.mediaDevices?.getUserMedia)return toast('Microphone access is not available in this runtime');if(mediaRecorder&&mediaRecorder.state==='recording')return;try{mediaStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});audioChunks=[];mediaRecorder=new MediaRecorder(mediaStream);mediaRecorder.ondataavailable=e=>{if(e.data.size)audioChunks.push(e.data)};mediaRecorder.onstop=processRecording;mediaRecorder.start();startVisualizer(mediaStream);$('#micBtn').classList.add('recording');$('#stopBtn').disabled=false;setVoiceState('Listening','Recording from your microphone. Press stop when you’re finished.')}catch(e){setVoiceState('Error','Allow microphone access in Windows/browser permissions and try again.');toast('Microphone permission denied or unavailable')}}
function stopRecording(){if(mediaRecorder&&mediaRecorder.state!=='inactive')mediaRecorder.stop();if(mediaStream)mediaStream.getTracks().forEach(t=>t.stop());mediaStream=null;stopVisualizer();$('#micBtn').classList.remove('recording');$('#stopBtn').disabled=true}
async function processRecording(){setVoiceState('Transcribing','Whisper is processing your recording locally.');try{const blob=new Blob(audioChunks,{type:mediaRecorder?.mimeType||'audio/webm'});if(!blob.size)throw new Error('No audio was recorded');const fd=new FormData();fd.append('audio',blob,'recording.webm');const r=await api('/api/transcribe',{method:'POST',body:fd});if(!r.text)throw new Error('No speech detected');await sendText(r.text)}catch(e){setVoiceState('Error',e.message);toast(e.message)}}
$('#micBtn').onclick=()=>mediaRecorder&&mediaRecorder.state==='recording'?stopRecording():startRecording();$('#stopBtn').onclick=()=>{if(mediaRecorder&&mediaRecorder.state==='recording')stopRecording();else stopAudio();setVoiceState('Ready','Press the microphone and speak naturally.')};
$('#newConversationBtn').onclick=()=>{stopEverything();currentConversation=null;renderMessages([]);setVoiceState('Ready','Press the microphone and speak naturally.');toast('New local conversation started')};
function stopEverything(){if(mediaRecorder&&mediaRecorder.state==='recording')stopRecording();stopAudio();stopVisualizer()}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function forceSignOut(message='Please sign in again'){currentUser=null;currentConversation=null;localStorage.removeItem('orivox_user');showAuth();toast(message)}
async function loadAll(){await Promise.all([loadStatus(),loadHistory(),loadProfile(),loadSettings()])}
async function boot(){applyTheme(localStorage.getItem('orivox_theme')||'system');if(!currentUser)return showAuth();try{currentUser=await api(`/api/auth/session/${currentUser.id}`);localStorage.setItem('orivox_user',JSON.stringify(currentUser));showApp()}catch{forceSignOut('Your saved local session could not be restored. Please sign in again.')}}
matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if((localStorage.getItem('orivox_theme')||'system')==='system')applyTheme('system')});
boot();
