const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let currentUser=JSON.parse(localStorage.getItem('orivox_user')||'null');
let currentConversation=null,mediaRecorder=null,mediaStream=null,audioChunks=[],audioCtx=null,analyser=null,animId=null,currentAudio=null,settings={};
let modelPollTimer=null;
const state={history:[],status:null};

function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),3600)}
async function api(url,opts={}){const headers={...(opts.headers||{})};if(opts.body&&!(opts.body instanceof FormData)&&!headers['Content-Type'])headers['Content-Type']='application/json';let r;try{r=await fetch(url,{...opts,headers})}catch{throw new Error('ORIVOX local service is unavailable. Restart ORIVOX and try again.')}if(!r.ok){let m=`Request failed (${r.status})`;try{const j=await r.json();m=j.detail||j.message||m}catch{}throw new Error(m)}const ct=r.headers.get('content-type')||'';return ct.includes('application/json')?r.json():r.blob()}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function applyTheme(mode){const dark=mode==='dark'||(mode==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.body.classList.toggle('dark',dark);localStorage.setItem('orivox_theme',mode);const t=$('#themeToggle');if(t)t.textContent=dark?'☾':'☼'}
function initials(name='ORIVOX'){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'O'}
function syncUserUI(){if(!currentUser)return;const mark=initials(currentUser.name);['#topAvatar','#profileAvatar'].forEach(id=>{const el=$(id);if(el)el.textContent=mark});const welcome=$('#welcome');if(welcome)welcome.innerHTML=`Welcome back, ${escapeHtml(currentUser.name)}.<br><em>ORIVOX is ready.</em>`}
function showAuth(){$('#auth').classList.remove('hidden');$('#app').classList.add('hidden')}
function showApp(){$('#auth').classList.add('hidden');$('#app').classList.remove('hidden');syncUserUI();switchView('dashboard');loadAll()}

const viewMeta={dashboard:['Overview','LOCAL AI WORKSPACE'],voice:['Voice Assistant','VOICE WORKSPACE'],history:['Conversations','YOUR LOCAL MEMORY'],profile:['Profile','LOCAL ACCOUNT'],settings:['Settings','MAKE ORIVOX YOURS'],about:['Help & About','HR-PRESENTS ORIVOX']};
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===name));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===name));const meta=viewMeta[name]||[name,'ORIVOX'];$('#pageTitle').textContent=meta[0];$('#pageEyebrow').textContent=meta[1];window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$$('[data-auth]').forEach(b=>b.addEventListener('click',()=>{const login=b.dataset.auth==='login';$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$('#loginForm').classList.toggle('hidden',!login);$('#registerForm').classList.toggle('hidden',login);$('#authHeading').textContent=login?'Sign in to your workspace':'Create your local workspace'}));
$$('[data-toggle-password]').forEach(b=>b.onclick=()=>{const i=document.getElementById(b.dataset.togglePassword);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Show':'Hide'});
function setFormBusy(form,busy,label){const btn=form.querySelector('button[type="submit"]');if(!btn)return;if(!btn.dataset.original)btn.dataset.original=btn.innerHTML;btn.disabled=busy;btn.innerHTML=busy?label:btn.dataset.original}

$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;setFormBusy(f,true,'Signing in…');try{const u=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value})});currentUser=u;localStorage.setItem('orivox_user',JSON.stringify(u));toast(`Welcome back, ${u.name}`);showApp()}catch(err){toast(err.message)}finally{setFormBusy(f,false,'')}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;if($('#registerPassword').value!==$('#registerConfirm').value)return toast('Passwords do not match');setFormBusy(f,true,'Creating local account…');try{const u=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:$('#registerName').value.trim(),email:$('#registerEmail').value.trim(),password:$('#registerPassword').value})});currentUser=u;localStorage.setItem('orivox_user',JSON.stringify(u));toast('Your local ORIVOX account is ready');showApp()}catch(err){toast(err.message)}finally{setFormBusy(f,false,'')}};
$('#logoutBtn').onclick=()=>{stopEverything();currentUser=null;currentConversation=null;state.history=[];localStorage.removeItem('orivox_user');showAuth();toast('Signed out of this local workspace')};

function statusLabel(v){return String(v||'unknown').replace(/_/g,' ')}
function formatBytes(n){n=Number(n||0);if(!n)return 'Preparing download…';const units=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<units.length-1){n/=1024;i++}return `${n>=10||i===0?n.toFixed(0):n.toFixed(1)} ${units[i]}`}
function updateModelProgress(models={}){
  const model=models.ai_model||state.status?.llm||'Local model';
  const ai=models.ai||'checking';
  const percent=Math.max(0,Math.min(100,Number(models.ai_download_percent||0)));
  const completed=Number(models.ai_download_completed||0),total=Number(models.ai_download_total||0);
  const phase=models.ai_download_status||statusLabel(ai);
  const downloading=ai==='downloading';
  const banner=$('#modelDownloadBanner'),voice=$('#voiceModelSetup');
  [banner,voice].forEach(el=>el&&el.classList.toggle('hidden',!downloading));
  if($('#modelDownloadName'))$('#modelDownloadName').textContent=model;
  if($('#modelDownloadPhase'))$('#modelDownloadPhase').textContent=phase;
  if($('#modelDownloadPercent'))$('#modelDownloadPercent').textContent=`${Math.round(percent)}%`;
  if($('#modelDownloadBar'))$('#modelDownloadBar').style.width=`${percent}%`;
  if($('#modelDownloadSize'))$('#modelDownloadSize').textContent=total?`${formatBytes(completed)} of ${formatBytes(total)} downloaded • one-time local setup`:'ORIVOX is preparing the model download on this computer.';
  if($('#voiceModelName'))$('#voiceModelName').textContent=model;
  if($('#voiceModelPercent'))$('#voiceModelPercent').textContent=`${Math.round(percent)}%`;
  if($('#voiceModelBar'))$('#voiceModelBar').style.width=`${percent}%`;
  if($('#voiceModelPhase'))$('#voiceModelPhase').textContent=total?`${phase} • ${formatBytes(completed)} / ${formatBytes(total)}`:phase;
  if($('#settingsModelState'))$('#settingsModelState').textContent=downloading?`Downloading ${Math.round(percent)}% — ${phase}`:ai==='ready'?'Installed locally and ready':ai==='unavailable'?'Local AI engine unavailable':statusLabel(ai);
  if(downloading)setVoiceState('Downloading',`First-time setup: ORIVOX is downloading ${model} to this computer.`);
}
async function loadStatus(silent=false){try{state.status=await api('/api/status');const model=state.status.llm||state.status.models?.ai_model||'Local model';$('#statModel').textContent=model;$('#settingsModel').textContent=model;$('#aboutVersion').textContent=state.status.version||'—';const m=state.status.models||{};const core=['whisper','ai','kokoro'];$('#modelStatus').innerHTML=core.map(k=>`<div class="model-line"><span>${k.toUpperCase()}</span><strong class="${escapeHtml(String(m[k]||'idle').split(':')[0])}">${escapeHtml(statusLabel(m[k]||'idle'))}</strong></div>`).join('');const ok=core.every(k=>['ready','idle','checking'].includes(String(m[k]||'idle')));$('#statusBadge').innerHTML=`<span class="live-dot"></span>${m.ai==='downloading'?'Downloading AI model':ok?'Local systems ready':'Check local models'}`;updateModelProgress(m)}catch(e){if(!silent){$('#statusBadge').textContent='Status unavailable';toast(e.message)}}}
function startModelPolling(){if(modelPollTimer)return;loadStatus(true);modelPollTimer=setInterval(()=>loadStatus(true),700)}
function stopModelPolling(){if(modelPollTimer){clearInterval(modelPollTimer);modelPollTimer=null}loadStatus(true)}

async function loadHistory(){if(!currentUser)return;try{state.history=await api(`/api/conversations/${currentUser.id}`);renderHistory();$('#statConversations').textContent=state.history.length;$('#statMessages').textContent=state.history.reduce((a,c)=>a+Number(c.message_count||0),0);$('#recentList').innerHTML=state.history.slice(0,5).map(c=>`<button class="list-row recent-button" onclick="openConversation(${c.id})"><strong>${escapeHtml(c.title)}</strong><span class="muted">${Number(c.message_count||0)} messages →</span></button>`).join('')||'<div class="empty-inline"><strong>No conversations yet</strong><span>Start your first voice conversation.</span></div>'}catch(e){if(e.message.toLowerCase().includes('session'))return forceSignOut(e.message);toast(e.message)}}
function renderHistory(){const q=($('#historySearch').value||'').toLowerCase();const rows=state.history.filter(c=>(c.title||'').toLowerCase().includes(q));$('#historyList').innerHTML=rows.map(c=>`<article class="panel history-item"><div><span class="kicker">LOCAL CONVERSATION</span><h3>${escapeHtml(c.title)}</h3><div class="muted">${Number(c.message_count||0)} messages${c.updated_at?` • ${formatDate(c.updated_at)}`:''}</div></div><div class="history-actions"><button class="secondary" onclick="openConversation(${c.id})">Open</button><button class="secondary danger" onclick="deleteConversation(${c.id})">Delete</button></div></article>`).join('')||'<div class="panel empty-inline"><strong>No conversations found</strong><span>Your real ORIVOX history will appear here.</span></div>'}
function formatDate(v){try{return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(v))}catch{return''}}
window.openConversation=async id=>{try{const c=await api(`/api/conversations/${currentUser.id}/${id}`);currentConversation=c.id;renderMessages(c.messages||[]);switchView('voice');setVoiceState('Ready','Continue this conversation by speaking or typing.')}catch(e){toast(e.message)}};
window.deleteConversation=async id=>{if(!confirm('Delete this local conversation permanently?'))return;try{await api(`/api/conversations/${currentUser.id}/${id}`,{method:'DELETE'});if(currentConversation===id){currentConversation=null;renderMessages([])}toast('Conversation deleted');await loadHistory()}catch(e){toast(e.message)}};
$('#historySearch').oninput=renderHistory;$('#refreshHistory').onclick=loadHistory;

async function loadProfile(){try{const p=await api(`/api/profile/${currentUser.id}`);currentUser=p;localStorage.setItem('orivox_user',JSON.stringify(p));$('#profileName').value=p.name;$('#profileEmail').value=p.email;syncUserUI()}catch(e){if(e.message.toLowerCase().includes('session'))return forceSignOut(e.message);toast(e.message)}}
$('#profileForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;setFormBusy(f,true,'Saving…');try{const p=await api(`/api/profile/${currentUser.id}`,{method:'PUT',body:JSON.stringify({name:$('#profileName').value.trim(),email:$('#profileEmail').value.trim(),current_password:$('#profileCurrentPassword').value||null,new_password:$('#profileNewPassword').value||null})});currentUser=p;localStorage.setItem('orivox_user',JSON.stringify(p));syncUserUI();$('#profileCurrentPassword').value='';$('#profileNewPassword').value='';toast('Profile changes saved locally')}catch(e){toast(e.message)}finally{setFormBusy(f,false,'')}};
async function loadSettings(){try{settings=await api(`/api/settings/${currentUser.id}`);$('#settingTheme').value=settings.theme||'system';$('#settingVoice').value=settings.voice||'af_heart';$('#settingSpeed').value=settings.speed||'1.0';$('#settingVolume').value=settings.volume||'1.0';$('#settingAutoSpeak').checked=settings.auto_speak!=='false';$('#settingSaveAudio').checked=settings.save_audio==='true';applyTheme(settings.theme||'system')}catch(e){toast(e.message)}}
$('#saveSettings').onclick=async()=>{const b=$('#saveSettings'),original=b.textContent;b.disabled=true;b.textContent='Saving…';const values={theme:$('#settingTheme').value,voice:$('#settingVoice').value,speed:$('#settingSpeed').value,volume:$('#settingVolume').value,auto_speak:$('#settingAutoSpeak').checked,save_audio:$('#settingSaveAudio').checked};try{settings=await api(`/api/settings/${currentUser.id}`,{method:'PUT',body:JSON.stringify({values})});applyTheme(settings.theme||values.theme);toast('Settings saved on this device')}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent=original}};
$('#themeToggle').onclick=()=>{const next=document.body.classList.contains('dark')?'light':'dark';applyTheme(next);if($('#settingTheme'))$('#settingTheme').value=next};

function emptyConversation(){return '<div class="empty-state"><span>✦</span><strong>Your conversation starts here</strong><p>Speak or type a message. Real messages will appear here and be saved to local history.</p></div>'}
function renderMessages(msgs){const box=$('#messages');box.innerHTML=msgs.length?msgs.map(m=>`<div class="message ${escapeHtml(m.role)}"><span>${m.role==='user'?'You':'ORIVOX'}</span>${escapeHtml(m.content)}</div>`).join(''):emptyConversation();box.scrollTop=box.scrollHeight}
function appendMessage(role,text){const box=$('#messages');if(box.querySelector('.empty-state'))box.innerHTML='';const d=document.createElement('div');d.className=`message ${role}`;const who=document.createElement('span');who.textContent=role==='user'?'You':'ORIVOX';d.appendChild(who);d.appendChild(document.createTextNode(text));box.appendChild(d);box.scrollTop=box.scrollHeight}
function setVoiceState(s,hint=''){if($('#voiceState'))$('#voiceState').textContent=s;if(hint&&$('#voiceHint'))$('#voiceHint').textContent=hint;const p=$('#voicePrompt');if(p){const map={Listening:'I’m listening…',Transcribing:'Turning your voice into text…',Thinking:'Thinking locally…',Downloading:'Setting up your local AI…',Speaking:'ORIVOX is speaking…',Error:'Something needs attention',Ready:'What would you like to talk about?'};p.textContent=map[s]||s}}
async function sendText(text){text=(text||'').trim();if(!text||!currentUser)return;appendMessage('user',text);setVoiceState('Thinking','Your local AI model is generating a response.');$('#sendBtn').disabled=true;startModelPolling();try{const r=await api('/api/chat',{method:'POST',body:JSON.stringify({user_id:currentUser.id,conversation_id:currentConversation,text})});currentConversation=r.conversation_id;const reply=r.text||r.response||'';appendMessage('assistant',reply);setVoiceState('Ready','Response complete. Continue speaking whenever you’re ready.');await loadHistory();if(settings.auto_speak!=='false'&&reply)await speak(reply)}catch(e){setVoiceState('Error',e.message);toast(e.message)}finally{$('#sendBtn').disabled=false;stopModelPolling()}}
$('#sendBtn').onclick=()=>{const t=$('#textInput').value;$('#textInput').value='';sendText(t)};$('#textInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#sendBtn').click()}});
async function speak(text){stopAudio();setVoiceState('Speaking','Kokoro is generating speech locally.');try{const blob=await api('/api/speech',{method:'POST',body:JSON.stringify({text,voice:settings.voice||'af_heart',speed:Number(settings.speed||1)})});const url=URL.createObjectURL(blob);currentAudio=new Audio(url);currentAudio.volume=Number(settings.volume||1);currentAudio.onended=()=>{URL.revokeObjectURL(url);currentAudio=null;setVoiceState('Ready','Press the microphone and speak naturally.')};await currentAudio.play()}catch(e){setVoiceState('Error',e.message);toast(e.message)}}
function stopAudio(){if(currentAudio){currentAudio.pause();currentAudio.currentTime=0;currentAudio=null}}
function stopVisualizer(){if(animId)cancelAnimationFrame(animId);animId=null;if($('#visualizer'))$('#visualizer').innerHTML='';if(audioCtx){audioCtx.close();audioCtx=null}}
function startVisualizer(stream){stopVisualizer();audioCtx=new (window.AudioContext||window.webkitAudioContext)();const src=audioCtx.createMediaStreamSource(stream);analyser=audioCtx.createAnalyser();analyser.fftSize=128;src.connect(analyser);const bars=Array.from({length:34},()=>{const b=document.createElement('div');b.className='bar';$('#visualizer').appendChild(b);return b});const data=new Uint8Array(analyser.frequencyBinCount);const draw=()=>{analyser.getByteFrequencyData(data);bars.forEach((b,i)=>b.style.height=`${Math.max(5,(data[(i*2)%data.length]||0)/2.25)}px`);animId=requestAnimationFrame(draw)};draw()}
async function startRecording(){stopAudio();if(!navigator.mediaDevices?.getUserMedia)return toast('Microphone access is not available in this browser');if(mediaRecorder&&mediaRecorder.state==='recording')return;try{mediaStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});audioChunks=[];mediaRecorder=new MediaRecorder(mediaStream);mediaRecorder.ondataavailable=e=>{if(e.data.size)audioChunks.push(e.data)};mediaRecorder.onstop=processRecording;mediaRecorder.start();startVisualizer(mediaStream);$('#micBtn').classList.add('recording');$('#stopBtn').disabled=false;setVoiceState('Listening','Recording from your microphone. Press stop when you’re finished.')}catch(e){setVoiceState('Error','Allow microphone access in Windows/browser permissions and try again.');toast('Microphone permission denied or unavailable')}}
function stopRecording(){if(mediaRecorder&&mediaRecorder.state!=='inactive')mediaRecorder.stop();if(mediaStream)mediaStream.getTracks().forEach(t=>t.stop());mediaStream=null;stopVisualizer();$('#micBtn').classList.remove('recording');$('#stopBtn').disabled=true}
async function processRecording(){setVoiceState('Transcribing','Whisper is processing your recording locally.');try{const blob=new Blob(audioChunks,{type:mediaRecorder?.mimeType||'audio/webm'});if(!blob.size)throw new Error('No audio was recorded');const fd=new FormData();fd.append('audio',blob,'recording.webm');const r=await api('/api/transcribe',{method:'POST',body:fd});if(!r.text)throw new Error('No speech detected');await sendText(r.text)}catch(e){setVoiceState('Error',e.message);toast(e.message)}}
$('#micBtn').onclick=()=>mediaRecorder&&mediaRecorder.state==='recording'?stopRecording():startRecording();$('#stopBtn').onclick=()=>{if(mediaRecorder&&mediaRecorder.state==='recording')stopRecording();else stopAudio();setVoiceState('Ready','Press the microphone and speak naturally.')};
$('#newConversationBtn').onclick=()=>{currentConversation=null;renderMessages([]);setVoiceState('Ready','Start a new private conversation.')};
function stopEverything(){if(mediaRecorder&&mediaRecorder.state==='recording')mediaRecorder.stop();if(mediaStream)mediaStream.getTracks().forEach(t=>t.stop());mediaStream=null;stopVisualizer();stopAudio();stopModelPolling()}
function forceSignOut(msg){currentUser=null;currentConversation=null;localStorage.removeItem('orivox_user');showAuth();toast(msg)}
async function loadAll(){await Promise.all([loadStatus(),loadHistory(),loadProfile(),loadSettings()])}

applyTheme(localStorage.getItem('orivox_theme')||'system');
if(currentUser){api(`/api/auth/session/${currentUser.id}`).then(showApp).catch(()=>{currentUser=null;localStorage.removeItem('orivox_user');showAuth()})}else showAuth();
