const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let currentUser=JSON.parse(localStorage.getItem('orivox_user')||'null');
let currentConversation=null, mediaRecorder=null, mediaStream=null, audioChunks=[], audioCtx=null, analyser=null, animId=null, currentAudio=null, settings={};
const state={history:[],status:null};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
async function api(url,opts={}){
  const headers={...(opts.headers||{})};
  if(opts.body && !(opts.body instanceof FormData) && !headers['Content-Type']) headers['Content-Type']='application/json';
  let r;
  try{r=await fetch(url,{...opts,headers})}catch(e){throw new Error('ORIVOX local service is unavailable. Restart the app and try again.')}
  if(!r.ok){let m=`Request failed (${r.status})`;try{const j=await r.json();m=j.detail||j.message||m}catch{}throw new Error(m)}
  const ct=r.headers.get('content-type')||'';return ct.includes('application/json')?r.json():r.blob();
}
function applyTheme(mode){const dark=mode==='dark'||(mode==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.body.classList.toggle('dark',dark);localStorage.setItem('orivox_theme',mode)}
function showAuth(){ $('#auth').classList.remove('hidden'); $('#app').classList.add('hidden') }
function showApp(){ $('#auth').classList.add('hidden'); $('#app').classList.remove('hidden'); $('#sidebarUser').textContent=currentUser.email; $('#welcome').textContent=`Welcome, ${currentUser.name}`; loadAll() }
function switchView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===name));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===name));$('#pageTitle').textContent=({dashboard:'Dashboard',voice:'Voice Assistant',history:'Conversation History',profile:'Profile',settings:'Settings',about:'About ORIVOX'})[name]||name}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$$('[data-auth]').forEach(b=>b.addEventListener('click',()=>{const login=b.dataset.auth==='login';$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$('#loginForm').classList.toggle('hidden',!login);$('#registerForm').classList.toggle('hidden',login)}));
$$('[data-toggle-password]').forEach(b=>b.onclick=()=>{const i=document.getElementById(b.dataset.togglePassword);i.type=i.type==='password'?'text':'password';b.textContent=i.type==='password'?'Show':'Hide'});
function setFormBusy(form,busy,label){const btn=form.querySelector('button[type="submit"]');if(!btn)return;if(!btn.dataset.original)btn.dataset.original=btn.textContent;btn.disabled=busy;btn.textContent=busy?label:btn.dataset.original}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;setFormBusy(form,true,'Signing in…');try{const u=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value})});currentUser=u;localStorage.setItem('orivox_user',JSON.stringify(u));toast('Login successful');showApp()}catch(err){toast(err.message)}finally{setFormBusy(form,false,'')}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;if($('#registerPassword').value!==$('#registerConfirm').value)return toast('Passwords do not match');setFormBusy(form,true,'Creating account…');try{const u=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name:$('#registerName').value.trim(),email:$('#registerEmail').value.trim(),password:$('#registerPassword').value})});currentUser=u;localStorage.setItem('orivox_user',JSON.stringify(u));toast('Account created');showApp()}catch(err){toast(err.message)}finally{setFormBusy(form,false,'')}};
$('#logoutBtn').onclick=()=>{stopEverything();currentUser=null;currentConversation=null;state.history=[];localStorage.removeItem('orivox_user');showAuth();toast('Logged out')};
async function loadStatus(){try{state.status=await api('/api/status');$('#statModel').textContent=state.status.llm||'Local model';$('#settingsModel').textContent=state.status.llm||'Local model';$('#aboutVersion').textContent=state.status.version||'—';const entries=Object.entries(state.status.models||{});$('#modelStatus').innerHTML=entries.length?entries.map(([k,v])=>`<div class="model-line"><span>${k.toUpperCase()}</span><strong class="${v}">${v}</strong></div>`).join(''):'<div class="muted">Model status will appear after first use.</div>';const ok=entries.length===0||entries.every(([,v])=>v==='ready'||v==='idle');$('#statusBadge').textContent=ok?'Local AI ready':'Check local models'}catch(e){$('#statusBadge').textContent='Status unavailable'}}
async function loadHistory(){if(!currentUser)return;try{state.history=await api(`/api/conversations/${currentUser.id}`);renderHistory();$('#statConversations').textContent=state.history.length;$('#statMessages').textContent=state.history.reduce((a,c)=>a+Number(c.message_count||0),0);$('#recentList').innerHTML=state.history.slice(0,4).map(c=>`<div class="list-row"><strong>${escapeHtml(c.title)}</strong><div class="muted">${Number(c.message_count||0)} messages</div></div>`).join('')||'<div class="muted">No conversations yet.</div>'}catch(e){if(e.message.toLowerCase().includes('session'))return forceSignOut(e.message);toast(e.message)}}
function renderHistory(){const q=$('#historySearch').value.toLowerCase();const rows=state.history.filter(c=>(c.title||'').toLowerCase().includes(q));$('#historyList').innerHTML=rows.map(c=>`<article class="card history-item"><div><h3>${escapeHtml(c.title)}</h3><div class="muted">${Number(c.message_count||0)} messages</div></div><div class="history-actions"><button class="ghost" onclick="openConversation(${c.id})">Open</button><button class="ghost" onclick="deleteConversation(${c.id})">Delete</button></div></article>`).join('')||'<div class="card muted">No conversations found.</div>'}
window.openConversation=async id=>{try{const c=await api(`/api/conversations/${currentUser.id}/${id}`);currentConversation=c.id;renderMessages(c.messages||[]);switchView('voice')}catch(e){toast(e.message)}};
window.deleteConversation=async id=>{if(!confirm('Delete this conversation?'))return;try{await api(`/api/conversations/${currentUser.id}/${id}`,{method:'DELETE'});if(currentConversation===id){currentConversation=null;renderMessages([])}toast('Conversation deleted');await loadHistory()}catch(e){toast(e.message)}};
$('#historySearch').oninput=renderHistory;$('#refreshHistory').onclick=loadHistory;
async function loadProfile(){try{const p=await api(`/api/profile/${currentUser.id}`);currentUser=p;localStorage.setItem('orivox_user',JSON.stringify(p));$('#profileName').value=p.name;$('#profileEmail').value=p.email;$('#sidebarUser').textContent=p.email;$('#welcome').textContent=`Welcome, ${p.name}`}catch(e){if(e.message.toLowerCase().includes('session'))return forceSignOut(e.message);toast(e.message)}}
$('#profileForm').onsubmit=async e=>{e.preventDefault();try{const p=await api(`/api/profile/${currentUser.id}`,{method:'PUT',body:JSON.stringify({name:$('#profileName').value,email:$('#profileEmail').value,current_password:$('#profileCurrentPassword').value||null,new_password:$('#profileNewPassword').value||null})});currentUser=p;localStorage.setItem('orivox_user',JSON.stringify(p));$('#sidebarUser').textContent=p.email;$('#welcome').textContent=`Welcome, ${p.name}`;$('#profileCurrentPassword').value='';$('#profileNewPassword').value='';toast('Profile updated')}catch(e){toast(e.message)}};
async function loadSettings(){try{settings=await api(`/api/settings/${currentUser.id}`);$('#settingTheme').value=settings.theme||'system';$('#settingVoice').value=settings.voice||'af_heart';$('#settingSpeed').value=settings.speed||'1.0';$('#settingVolume').value=settings.volume||'1.0';$('#settingAutoSpeak').checked=settings.auto_speak!=='false';$('#settingSaveAudio').checked=settings.save_audio==='true';applyTheme(settings.theme||'system')}catch(e){toast(e.message)}}
$('#saveSettings').onclick=async()=>{const values={theme:$('#settingTheme').value,voice:$('#settingVoice').value,speed:$('#settingSpeed').value,volume:$('#settingVolume').value,auto_speak:$('#settingAutoSpeak').checked,save_audio:$('#settingSaveAudio').checked};try{settings=await api(`/api/settings/${currentUser.id}`,{method:'PUT',body:JSON.stringify({values})});applyTheme(settings.theme||values.theme);toast('Settings saved')}catch(e){toast(e.message)}};
$('#themeToggle').onclick=()=>{const next=document.body.classList.contains('dark')?'light':'dark';applyTheme(next);$('#settingTheme').value=next};
function renderMessages(msgs){const box=$('#messages');if(!msgs.length){box.innerHTML='<div class="empty">Your conversation will appear here.</div>';return}box.innerHTML=msgs.map(m=>`<div class="message ${m.role}">${escapeHtml(m.content)}</div>`).join('');box.scrollTop=box.scrollHeight}
function appendMessage(role,text){const box=$('#messages');if(box.querySelector('.empty'))box.innerHTML='';const d=document.createElement('div');d.className=`message ${role}`;d.textContent=text;box.appendChild(d);box.scrollTop=box.scrollHeight}
function setVoiceState(s,hint=''){ $('#voiceState').textContent=s; if(hint)$('#voiceHint').textContent=hint }
async function sendText(text){text=(text||'').trim();if(!text||!currentUser)return;appendMessage('user',text);setVoiceState('Thinking','Local AI is generating a response…');$('#sendBtn').disabled=true;try{const r=await api('/api/chat',{method:'POST',body:JSON.stringify({user_id:currentUser.id,conversation_id:currentConversation,text})});currentConversation=r.conversation_id;const reply=r.text||r.response||'';appendMessage('assistant',reply);setVoiceState('Response ready','ORIVOX finished thinking.');await loadHistory();if(settings.auto_speak!=='false'&&reply)await speak(reply)}catch(e){setVoiceState('Error',e.message);toast(e.message)}finally{$('#sendBtn').disabled=false}}
$('#sendBtn').onclick=()=>{const t=$('#textInput').value;$('#textInput').value='';sendText(t)};$('#textInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();$('#sendBtn').click()}});
async function speak(text){stopAudio();setVoiceState('Speaking','Generating local Kokoro speech…');try{const blob=await api('/api/speech',{method:'POST',body:JSON.stringify({text,voice:settings.voice||'af_heart',speed:Number(settings.speed||1)})});currentAudio=new Audio(URL.createObjectURL(blob));currentAudio.volume=Number(settings.volume||1);currentAudio.onended=()=>{currentAudio=null;setVoiceState('Ready','Press to start recording')};await currentAudio.play()}catch(e){setVoiceState('Error',e.message);toast(e.message)}}
function stopAudio(){if(currentAudio){currentAudio.pause();currentAudio.currentTime=0;currentAudio=null}}
function stopVisualizer(){if(animId)cancelAnimationFrame(animId);animId=null;$('#visualizer').innerHTML='';if(audioCtx){audioCtx.close();audioCtx=null}}
function startVisualizer(stream){audioCtx=new (window.AudioContext||window.webkitAudioContext)();const src=audioCtx.createMediaStreamSource(stream);analyser=audioCtx.createAnalyser();analyser.fftSize=128;src.connect(analyser);const bars=Array.from({length:28},()=>{const b=document.createElement('div');b.className='bar';$('#visualizer').appendChild(b);return b});const data=new Uint8Array(analyser.frequencyBinCount);const draw=()=>{analyser.getByteFrequencyData(data);bars.forEach((b,i)=>b.style.height=`${Math.max(8,(data[i*2]||0)/2.2)}px`);animId=requestAnimationFrame(draw)};draw()}
async function startRecording(){stopAudio();if(!navigator.mediaDevices?.getUserMedia)return toast('Microphone access is not available in this runtime');try{mediaStream=await navigator.mediaDevices.getUserMedia({audio:true});audioChunks=[];mediaRecorder=new MediaRecorder(mediaStream);mediaRecorder.ondataavailable=e=>{if(e.data.size)audioChunks.push(e.data)};mediaRecorder.onstop=processRecording;mediaRecorder.start();startVisualizer(mediaStream);$('#micBtn').classList.add('recording');$('#stopBtn').disabled=false;setVoiceState('Listening','Recording from your microphone…')}catch(e){setVoiceState('Microphone unavailable','Allow microphone access and try again.');toast('Microphone permission denied or unavailable')}}
function stopRecording(){if(mediaRecorder&&mediaRecorder.state!=='inactive')mediaRecorder.stop();if(mediaStream)mediaStream.getTracks().forEach(t=>t.stop());mediaStream=null;stopVisualizer();$('#micBtn').classList.remove('recording');$('#stopBtn').disabled=true}
async function processRecording(){setVoiceState('Transcribing','Whisper is processing your recording…');try{const blob=new Blob(audioChunks,{type:mediaRecorder?.mimeType||'audio/webm'});if(!blob.size)throw new Error('No audio was recorded');const fd=new FormData();fd.append('audio',blob,'recording.webm');const r=await api('/api/transcribe',{method:'POST',body:fd});if(!r.text)throw new Error('No speech detected');await sendText(r.text)}catch(e){setVoiceState('Error',e.message);toast(e.message)}}
$('#micBtn').onclick=()=>mediaRecorder&&mediaRecorder.state==='recording'?stopRecording():startRecording();$('#stopBtn').onclick=()=>{if(mediaRecorder&&mediaRecorder.state==='recording')stopRecording();else stopAudio();setVoiceState('Ready','Press to start recording')};
$('#newConversationBtn').onclick=()=>{stopEverything();currentConversation=null;renderMessages([]);setVoiceState('Ready','Press to start recording');toast('New conversation')};
function stopEverything(){if(mediaRecorder&&mediaRecorder.state==='recording')stopRecording();stopAudio();stopVisualizer()}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function forceSignOut(message='Please sign in again'){currentUser=null;currentConversation=null;localStorage.removeItem('orivox_user');showAuth();toast(message)}
async function loadAll(){await Promise.all([loadStatus(),loadHistory(),loadProfile(),loadSettings()])}
async function boot(){applyTheme(localStorage.getItem('orivox_theme')||'system');if(!currentUser)return showAuth();try{currentUser=await api(`/api/auth/session/${currentUser.id}`);localStorage.setItem('orivox_user',JSON.stringify(currentUser));showApp()}catch(e){forceSignOut('Your saved session could not be restored. Please sign in again.')}}
boot();
